CREATE SCHEMA test;

DROP TABLE IF EXISTS test.patient;

CREATE TABLE test.patient (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(225),
    lastname VARCHAR(225),
    photo VARCHAR(5000),
    phone VARCHAR(14),
    address VARCHAR(225)
);
